apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-service
  labels:
    app: consumer-service
spec:
  selector:
    matchLabels:
      app: consumer-service
  template:
    metadata:
      labels:
        app: consumer-service
    spec:
      containers:
        - name: consumer-service
          imagePullPolicy: IfNotPresent
          image: bayraktarahmetenes/consumer-service:1.0.0
---
apiVersion: v1
kind: Service
metadata:
  name: consumer-service
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: consumer-service
  type: ClusterIP
